# From Yihui's knitr
# it is not really python, but there is no R support on Travis CI yet
language: python

# environment variables
env:
  - R_LIBS_USER=~/R

# install dependencies
install:
  - sudo apt-add-repository -y ppa:marutter/rdev
  - sudo apt-get update
  - sudo apt-get install r-base-dev qpdf texinfo texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - Rscript -e '.libPaths(); sessionInfo()'
#  - Rscript -e 'install.packages("FishMaps", dep = TRUE, repos = NULL)'

# build locally
build:
  - cd ..;\
  - R CMD build FishMaps
  - R CMD INSTALL FishMaps_0.2-0.tar.gz

# run tests
script:
   - R CMD check FishMaps_0.2-0.tar.gz
